# Generated by Django 5.0.4 on 2024-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='addressee',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='auditors_responsibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='basis_of_opinion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='introductory_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='managements_responsibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='opinion_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='scope_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
