# Generated by Django 5.0.4 on 2024-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0002_auditreport_addressee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditreport',
            old_name='title',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='addressee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
