# Generated by Django 5.0.4 on 2024-04-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='csv',
        ),
        migrations.AddField(
            model_name='csv',
            name='csv_file',
            field=models.FileField(default='CinemasCsv.csv', upload_to='uploads/'),
        ),
    ]
